version: '3.9'

services:
  shipping-ops-producer:
    build: .
    ports:
      - "8087:8087"
    depends_on:
      - redis
      - kafka

  redis:
    image: "redis:7.0-alpine"
    ports:
      - "6379:6379"

  kafka:
    image: "bitnami/kafka:3"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: "bitnami/zookeeper:3"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
